apiVersion: apps/v1
kind: Deployment
metadata:
  name: nikk
  labels:
    app: nikk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nikk
  template:
    metadata:
      labels:
        app: nikk
    spec:
      containers:
      - name: nikk-container
        image: nikk007/edureka-assign-6
        ports:
        - containerPort: 80
        volumeMounts:
          - name: host-mount
            mountPath: /var/www/html/
      volumes:
        - name: host-mount
          hostPath:
            path: /root/nikk/